# Site settings
title               : Zero-Based
description         : Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet dolorem quaerat nisi, exercitationem ducimus
                      ratione, ex voluptatibus cumque eaque accusamus praesentium dolor magni officiis ipsa. Similique, repellendus
                      porro! Nemo ipsa doloribus rem dolorum vitae. Temporibus perferendis suscipit excepturi odit exercitationem in eius
                      obcaecati esse facilis amet, iure et sit, id sed nostrum officia culpa! Rerum enim excepturi, laborum temporibus
                      quam qui numquam veniam odit?
repository          : zero-based/zero-based.github.io

# Alert
alert               : "[BETA] This site is still under development, the data used is only for testing purposes."