# Site settings
title               : Zero-Based
description         : We are a team of friends from Faculty of Computer and Information Sciences at Ain Shams University since 2017. 
                      We tried to make every project we worked on, a special one, using new tools and best practices.
repository          : zero-based/zero-based.github.io
color               : "#000000"
